version: '3.9'

services:

  flask-app:
    image: flask-app
    container_name: flask-app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5000:5000
    environment:
      FLASK_APP: flaskr/app.py
    networks:
      - flask-app-network
    restart: on-failure
    deploy:
      replicas: 1

networks:
    flask-app-network:
      driver: bridge
      name: flask-app-network