name: Snyk

on:
  push:
    branches:
      - 'master'
      - 'develop'

jobs:
  security:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python-3.8@master
        env:
          SNYK_TOKEN: ${{ env.SNYK_TOKEN }}