name: Snyk

on:
  push:
    branches:
      - 'master'
      - 'develop'
      - 'github_workflows'

jobs:
  security:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      
      - name: Prepare requirements for Snyk
        run: |
          python -m pip install .
          python -m pip freeze > requirements.txt

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python-3.8@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}