name: Snyk

on:
  push:
    branches:
      - 'master'
      - 'develop'

jobs:
  security:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}